[package]
name = "htloader"
version = "0.1.0"
authors = ["Totsugekitai <37617413+Totsugekitai@users.noreply.github.com>"]
edition = "2021"

[[bin]]
name = "htloader"
path = "main.rs"

[dependencies]
uefi = "0.11.0"
rlibc = "1"
x86_64 = "0.14.3"
htlib = { path = "../lib" }
